Details of the exercise
Kanyelings/p1-25-coding-challenges-ds pull request #14
Opened 2023-02-08 17:01 UTC by FlyntDenzel

2023-02-11 08:22 UTC, elroykanye requested changes
FIgure some way out to remove the build files from git. There is a massive 500+ file change here

2023-02-13 08:12 UTC, elroykanye commented
Hello @FlyntDenzel , nice work here. For further contributions, let us try to use .gitignore files in our projects. Thanks for the update

2023-02-13 08:12 UTC, elroykanye approved these changes

2023-02-13 08:12 UTC, merged

2023-02-13 09:13 UTC, FlyntDenzel commented
Understood